"""
added-junctions

Revision ID: 6a0dd11ad617
Revises: 19b8c89e8d73
Create Date: 2026-05-12 13:36:07.850474

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a0dd11ad617"
down_revision: Union[str, Sequence[str], None] = "19b8c89e8d73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmark_jd_junction",
        sa.Column("bookmark_id", sa.Integer(), nullable=False),
        sa.Column("jd_node_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bookmark_id"],
            ["bookmarks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["jd_node_id"],
            ["jd_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("bookmark_id", "jd_node_id"),
    )
    op.drop_constraint(op.f("bookmarks_jd_id_fkey"), "bookmarks", type_="foreignkey")
    op.drop_column("bookmarks", "jd_id")
    op.add_column(
        "users",
        sa.Column("contact_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("users", sa.Column("role", sa.TEXT(), nullable=False))
    op.add_column(
        "users",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column("users", sa.Column("disabled", sa.BOOLEAN(), nullable=False))
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("users", "disabled")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "role")
    op.drop_column("users", "contact_number")
    op.add_column(
        "bookmarks",
        sa.Column("jd_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("bookmarks_jd_id_fkey"),
        "bookmarks",
        "jd_nodes",
        ["jd_id"],
        ["id"],
    )
    op.drop_table("bookmark_jd_junction")
    # ### end Alembic commands ###
