"""
fix-user-contact-number-email-unique-and-add-user-theme

Revision ID: 7f6d3d7c649f
Revises: 6a0dd11ad617
Create Date: 2026-05-25 16:22:50.002768

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f6d3d7c649f"
down_revision: Union[str, Sequence[str], None] = "6a0dd11ad617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("theme", sa.TEXT(), nullable=False))
    op.alter_column(
        "users",
        "contact_number",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["contact_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "contact_number",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("users", "theme")
    # ### end Alembic commands ###
