"""
implement_e2ee

Revision ID: 9abd8e1a114b
Revises: 7f6d3d7c649f
Create Date: 2026-05-28 19:25:27.200619

"""

import sys
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from alltheutils.utils import parent_dir_nth_times

sys.path.insert(0, parent_dir_nth_times(__file__, 4))

import src.db.encrypted_type

# revision identifiers, used by Alembic.
revision: str = "9abd8e1a114b"
down_revision: Union[str, Sequence[str], None] = "7f6d3d7c649f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bookmarks",
        "title",
        existing_type=sa.VARCHAR(length=256),
        type_=src.db.encrypted_type.EncryptedType(),
        nullable=False,
    )
    op.alter_column(
        "bookmarks",
        "url",
        existing_type=sa.VARCHAR(),
        type_=src.db.encrypted_type.EncryptedType(),
        existing_nullable=False,
    )
    op.alter_column(
        "bookmarks",
        "note",
        existing_type=sa.VARCHAR(),
        type_=src.db.encrypted_type.EncryptedType(),
        existing_nullable=True,
    )
    op.alter_column(
        "tags",
        "title",
        existing_type=sa.VARCHAR(length=32),
        type_=src.db.encrypted_type.EncryptedType(),
        existing_nullable=False,
    )
    op.alter_column(
        "tags",
        "color",
        existing_type=sa.VARCHAR(length=16),
        type_=src.db.encrypted_type.EncryptedType(),
        nullable=True,
    )
    op.alter_column(
        "tags",
        "note",
        existing_type=sa.VARCHAR(),
        type_=src.db.encrypted_type.EncryptedType(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tags",
        "note",
        existing_type=src.db.encrypted_type.EncryptedType(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "tags",
        "color",
        existing_type=src.db.encrypted_type.EncryptedType(),
        type_=sa.VARCHAR(length=16),
        nullable=False,
    )
    op.alter_column(
        "tags",
        "title",
        existing_type=src.db.encrypted_type.EncryptedType(),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "bookmarks",
        "note",
        existing_type=src.db.encrypted_type.EncryptedType(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "bookmarks",
        "url",
        existing_type=src.db.encrypted_type.EncryptedType(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "bookmarks",
        "title",
        existing_type=src.db.encrypted_type.EncryptedType(),
        type_=sa.VARCHAR(length=256),
        nullable=True,
    )
    # ### end Alembic commands ###
