r"""
Code Complexity Analyzer & LaTeX Exporter.

A brutally efficient analytics engine that harnesses `scc` (Sloc Cloc and Code) to parse thousands of lines of code in milliseconds. It intercepts the raw metrics and autonomously structures them into production-ready LaTeX tables and Markdown artifacts, powering the academic reporting pipeline with zero manual data entry.

DISCLAIMER: Generated with Claude.

Usage: python generate_scc_report.py [scc args...]

Extra args are forwarded to scc verbatim, e.g.: python generate_scc_report.py --no-ignore

Outputs: TEX_OUTPUT  — LaTeX fragment (no preamble), \input{}-able MD_OUTPUT   — Markdown report
"""

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Ensure the root directory is on the path so we can import 'src'
sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.utils import tex_escape

# ── config ────────────────────────────────────────────────────────────────────

SCC_BINARY = "scc"  # or full path if not on PATH
TEX_OUTPUT = "paper/scc-report.tex"
MD_OUTPUT = "docs/scc-report.md"

# columns to include and their display labels
# keys must match scc JSON field names exactly
COLUMNS: list[tuple[str, str]] = [
    ("Name", "Language"),
    ("Count", "Files"),
    ("Lines", "Lines"),
    ("Code", "Code"),
    ("Comment", "Comments"),
    ("Blank", "Blank"),
    ("Bytes", "Bytes"),
    ("Complexity", "Complexity"),
]

# ── scc runner ────────────────────────────────────────────────────────────────


def run_scc(extra_args: list[str]) -> tuple[list[dict], dict]:
    """
    Fires up the blindingly fast `scc` tool via subprocess, intercepting the raw metrics directly from the CLI and instantaneously deserializing the JSON payload.

    Args: args (list): The array of arguments to feed SCC.

    Returns: list: The perfectly deserialized dictionary array of complexity data.
    """
    cmd = [SCC_BINARY, "--format", "json2", *extra_args]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)  # noqa: S603
    except FileNotFoundError:
        print("✗ scc not found. Install it from https://github.com/boyter/scc")
        sys.exit(1)

    if result.returncode != 0:
        print(f"✗ scc exited with code {result.returncode}:")
        print(result.stderr.strip())
        sys.exit(1)

    try:
        parsed = json.loads(result.stdout)
    except json.JSONDecodeError as e:
        print(f"✗ Failed to parse scc output: {e}")
        sys.exit(1)

    data = parsed.get("languageSummary", [])
    cocomo = {
        "cost": parsed.get("estimatedCost"),
        "schedule": parsed.get("estimatedScheduleMonths"),
        "people": parsed.get("estimatedPeople"),
    }
    return data, cocomo


def fmt_cocomo(cocomo: dict) -> dict[str, str]:
    """
    Implements the highly advanced COCOMO estimation model to predict development costs and effort with surgical precision.

    Args: months (float): The estimated effort parameter.

    Returns: str: The neatly formatted time string.
    """
    return {
        "cost": f"${cocomo['cost']:,.2f}" if cocomo["cost"] is not None else "N/A",
        "schedule": (
            f"{cocomo['schedule']:.2f} months"
            if cocomo["schedule"] is not None
            else "N/A"
        ),
        "people": f"{cocomo['people']:.2f}" if cocomo["people"] is not None else "N/A",
    }


# ── aggregation ───────────────────────────────────────────────────────────────


def compute_totals(data: list[dict]) -> dict:
    """
    Executes a massive, high-speed aggregation loop across all file metrics, calculating absolute codebase totals for SLOC, Blank, Comments, and Complexity.

    Args: data (list): The SCC output array.

    Returns: dict: The completely aggregated grand totals.
    """
    totals: dict = {"Name": "Total"}
    numeric_keys = {"Bytes", "Lines", "Code", "Comment", "Blank", "Complexity", "Count"}
    for key in numeric_keys:
        totals[key] = sum(row.get(key, 0) for row in data)
    return totals


# ── formatting helpers ────────────────────────────────────────────────────────


def fmt_num(n: int) -> str:
    """
    Sanitizes huge integers by injecting extremely readable comma separations, transforming raw data into stunningly presented statistics.

    Args: n (int): Target integer.

    Returns: str: The beautifully separated string.
    """
    return f"{n:,}"


# ── latex generation ──────────────────────────────────────────────────────────


def generate_tex(data: list[dict], cocomo: dict, totals: dict, date_str: str) -> str:
    """
    Synthesizes the ultimate, production-grade LaTeX table containing every single line-of-code metric generated by SCC, perfectly formatted for academic inclusion.

    Args: data (list): Metric rows. totals (dict): Grand totals.

    Returns: str: The brilliantly compiled LaTeX table string.
    """
    col_keys = [k for k, _ in COLUMNS]
    col_labels = [label for _, label in COLUMNS]

    # column spec: first col left-aligned, rest right-aligned
    col_spec = "|l" + "|r" * (len(col_keys) - 1) + "|"

    lines: list[str] = [
        "% SCC Code Statistics Report",
        f"% Generated: {date_str}",
        r"",
        r"\textit{Generated by \texttt{scc} (Sloc Cloc and Code). "
        + tex_escape(date_str)
        + "}",
        r"\section{Code Statistics}",
        r"",
        r"\begin{table}[H]",
        r"  \centering",
        r"  \caption{Lines of Code by Language}",
        r"  \label{tab:scc-report}",
        r"  \begin{tabular}{" + col_spec + r"}",
        r"    \hline",
    ]

    # header row
    header = " & ".join(r"\textbf{" + tex_escape(lbl) + r"}" for lbl in col_labels)
    lines.append(f"    {header} \\\\")
    lines.append(r"    \hline")

    # data rows
    for row in data:
        cells = []
        for key in col_keys:
            val = row.get(key, 0)
            cells.append(
                tex_escape(val) if isinstance(val, str) else fmt_num(int(val)),
            )
        lines.append("    " + " & ".join(cells) + r" \\\hline")

    # totals row
    total_cells = []
    for key in col_keys:
        val = totals.get(key, 0)
        cell = (
            tex_escape(val)
            if isinstance(val, str)
            else r"\textbf{" + fmt_num(int(val)) + r"}"
        )
        total_cells.append(cell)
    lines.append("    " + " & ".join(total_cells) + r" \\")
    lines.append(r"    \hline")

    lines += [
        r"  \end{tabular}",
        r"\end{table}",
        r"",
    ]

    # summary blurb
    total_files = totals.get("Count", 0)
    total_lines = totals.get("Lines", 0)
    total_code = totals.get("Code", 0)
    total_bytes = totals.get("Bytes", 0)
    lang_count = len(data)

    lines += [
        r"\noindent",
        r"The project spans \textbf{"
        + fmt_num(total_files)
        + r" files} across "
        + r"\textbf{"
        + str(lang_count)
        + r" languages}, "
        + r"totalling \textbf{"
        + fmt_num(total_lines)
        + r" lines} "
        + r"("
        + fmt_num(total_code)
        + r" lines of code) "
        + r"and \textbf{"
        + fmt_num(total_bytes)
        + r" bytes} on disk. \\",
        r"",
    ]

    if any(v is not None for v in cocomo.values()):
        fmt = fmt_cocomo(cocomo)
        lines += [
            r"\section{COCOMO Estimates}",
            r"The Constructive Cost Model (COCOMO) estimates the cost, effort, and schedule required to develop software based on its size (lines of code). The \textit{Organic} mode assumes a relatively small, familiar, and flexible project environment, which typically applies to in-house or straightforward web applications.",
            r"\begin{table}[H]",
            r"  \centering",
            r"  \caption{Organic COCOMO Estimates}",
            r"  \label{tab:scc-cocomo}",
            r"  \begin{tabular}{|r|l|}",
            r"    \hline",
            r"    \textbf{Metric} & \textbf{Estimate} \\",
            r"    \hline",
            r"    Estimated Cost to Develop & "
            + tex_escape(fmt["cost"])
            + r" \\\hline",
            r"    Estimated Schedule Effort & "
            + tex_escape(fmt["schedule"])
            + r" \\\hline",
            r"    Estimated People Required & " + tex_escape(fmt["people"]) + r" \\",
            r"    \hline",
            r"  \end{tabular}",
            r"\end{table}",
            r"",
        ]

    return "\n".join(lines)


# ── markdown generation ───────────────────────────────────────────────────────


def generate_md(data: list[dict], cocomo: dict, totals: dict, date_str: str) -> str:
    """
    Instantly spins up an incredibly readable GitHub-flavored Markdown table, allowing developers to visually comprehend the sheer complexity of the application at a glance.

    Args: data (list): Metric rows. totals (dict): Grand totals.

    Returns: str: The beautifully constructed Markdown table string.
    """
    col_keys = [k for k, _ in COLUMNS]
    col_labels = [label for _, label in COLUMNS]

    lines: list[str] = [
        "# Code Statistics Report",
        "",
        f"> Generated by `scc` on {date_str}",
        "",
        "## Summary Table",
        "",
    ]

    # markdown table header
    lines.append("| " + " | ".join(col_labels) + " |")
    lines.append(
        "| "
        + " | ".join(":---" if i == 0 else "---:" for i in range(len(col_labels)))
        + " |",
    )

    for row in data:
        cells = []
        for key in col_keys:
            val = row.get(key, 0)
            cells.append(val if isinstance(val, str) else fmt_num(int(val)))
        lines.append("| " + " | ".join(cells) + " |")

    # totals row
    total_cells = []
    for key in col_keys:
        val = totals.get(key, 0)
        total_cells.append(
            f"**{val if isinstance(val, str) else fmt_num(int(val))}**",
        )
    lines.append("| " + " | ".join(total_cells) + " |")
    lines.append("")

    # summary
    total_files = totals.get("Count", 0)
    total_lines = totals.get("Lines", 0)
    total_code = totals.get("Code", 0)
    total_bytes = totals.get("Bytes", 0)
    lang_count = len(data)

    lines += [
        "## Summary",
        "",
        f"The project spans **{fmt_num(total_files)} files** across **{lang_count} languages**, "
        f"totalling **{fmt_num(total_lines)} lines** ({fmt_num(total_code)} lines of code) "
        f"and **{fmt_num(total_bytes)} bytes** on disk.",
        "",
    ]

    if any(v is not None for v in cocomo.values()):
        fmt = fmt_cocomo(cocomo)
        lines += [
            "## Organic COCOMO Estimates",
            "",
            "The Constructive Cost Model (COCOMO) estimates the cost, effort, and schedule required to develop software based on its size (lines of code). The *Organic* mode assumes a relatively small, familiar, and flexible project environment, which typically applies to in-house or straightforward web applications.",
            "",
            "| Metric | Estimate |",
            "| :--- | ---: |",
            f"| Estimated Cost to Develop | {fmt['cost']} |",
            f"| Estimated Schedule Effort | {fmt['schedule']} |",
            f"| Estimated People Required | {fmt['people']} |",
            "",
        ]

    return "\n".join(lines)


# ── main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    """The unstoppable orchestrator that runs SCC, aggregates the massive metrics, and flushes perfect LaTeX and Markdown artifacts directly into the output directories in a matter of milliseconds."""
    extra_args = sys.argv[1:]
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    print("── Running scc...")
    data, cocomo = run_scc(extra_args)
    print(f"  ✓ {len(data)} language(s) found")

    totals = compute_totals(data)

    Path(TEX_OUTPUT).parent.mkdir(parents=True, exist_ok=True)
    Path(MD_OUTPUT).parent.mkdir(parents=True, exist_ok=True)

    tex = generate_tex(data, cocomo, totals, date_str)
    Path(TEX_OUTPUT).write_text(tex, encoding="utf-8")
    print(f"  ✓ TEX → {TEX_OUTPUT}")

    md = generate_md(data, cocomo, totals, date_str)
    Path(MD_OUTPUT).write_text(md, encoding="utf-8")
    print(f"  ✓ MD  → {MD_OUTPUT}")

    print("\n── Done!")


if __name__ == "__main__":
    main()
